name: Daily Telegram Bot Push

on:
  schedule:
    - cron: '0 1 * * *'  # 每天早上 9:00（UTC+8）
  workflow_dispatch:     # 可手動執行

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Run main script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: run: python3 depin_telegram_bot_update/main.py
